/**
 * Mock Finis used for Free Mode and as fallback opponents.
 *
 * Once real Finiliar metadata is available, swap this for a loader
 * that reads from the original Finiliar collection (modelUrl,
 * animationSet, tokenId, ownerAddress).
 */
export const mockFinis = [
    {
        id: "fini-eth-1",
        tokenId: "1001",
        name: "Soft Gwei",
        family: "ETH",
        level: 1,
        xp: 0,
        strength: 5,
        maxHealth: 18,
        currentHealth: 18,
        speed: 4,
        defense: 4,
        volatilityAffinity: 0.4,
        cuteness: 0.7,
        passiveAbility: "COMPOUND",
    },
    {
        id: "fini-sol-1",
        tokenId: "2001",
        name: "Fast Wick",
        family: "SOL",
        level: 1,
        xp: 0,
        strength: 7,
        maxHealth: 14,
        currentHealth: 14,
        speed: 8,
        defense: 2,
        volatilityAffinity: 0.8,
        cuteness: 0.6,
        passiveAbility: "HIGH_THROUGHPUT",
    },
    {
        id: "fini-btc-1",
        tokenId: "3001",
        name: "Old Orange",
        family: "BTC",
        level: 1,
        xp: 0,
        strength: 5,
        maxHealth: 24,
        currentHealth: 24,
        speed: 2,
        defense: 7,
        volatilityAffinity: 0.2,
        cuteness: 0.4,
        passiveAbility: "DIAMOND_BODY",
    },
    {
        id: "fini-doge-1",
        tokenId: "4001",
        name: "Laugh Candle",
        family: "DOGE",
        level: 1,
        xp: 0,
        strength: 6,
        maxHealth: 16,
        currentHealth: 16,
        speed: 5,
        defense: 2,
        volatilityAffinity: 1.0,
        cuteness: 1.0,
        passiveAbility: "MEME_SPIKE",
    },
    {
        id: "fini-link-1",
        tokenId: "5001",
        name: "Oracle Pup",
        family: "LINK",
        level: 1,
        xp: 0,
        strength: 4,
        maxHealth: 18,
        currentHealth: 18,
        speed: 4,
        defense: 5,
        volatilityAffinity: 0.5,
        cuteness: 0.5,
        passiveAbility: "ORACLE",
    },
    {
        id: "fini-avax-1",
        tokenId: "6001",
        name: "Snowball",
        family: "AVAX",
        level: 1,
        xp: 0,
        strength: 7,
        maxHealth: 15,
        currentHealth: 15,
        speed: 5,
        defense: 3,
        volatilityAffinity: 0.7,
        cuteness: 0.6,
        passiveAbility: "AVALANCHE",
    },
    {
        id: "fini-uni-1",
        tokenId: "7001",
        name: "Swap Spirit",
        family: "UNI",
        level: 1,
        xp: 0,
        strength: 5,
        maxHealth: 17,
        currentHealth: 17,
        speed: 6,
        defense: 3,
        volatilityAffinity: 0.6,
        cuteness: 0.7,
        passiveAbility: "SWAP",
    },
    {
        id: "fini-bnb-1",
        tokenId: "8001",
        name: "Fee Burner",
        family: "BNB",
        level: 1,
        xp: 0,
        strength: 6,
        maxHealth: 17,
        currentHealth: 17,
        speed: 4,
        defense: 4,
        volatilityAffinity: 0.4,
        cuteness: 0.4,
        passiveAbility: "FEE_BURN",
    },
    {
        id: "fini-matic-1",
        tokenId: "9001",
        name: "Layer Layer",
        family: "MATIC",
        level: 1,
        xp: 0,
        strength: 5,
        maxHealth: 16,
        currentHealth: 16,
        speed: 6,
        defense: 4,
        volatilityAffinity: 0.5,
        cuteness: 0.6,
        passiveAbility: "SCALING",
    },
    {
        id: "fini-xtz-1",
        tokenId: "10001",
        name: "Self Amender",
        family: "XTZ",
        level: 1,
        xp: 0,
        strength: 5,
        maxHealth: 19,
        currentHealth: 19,
        speed: 4,
        defense: 5,
        volatilityAffinity: 0.5,
        cuteness: 0.5,
        passiveAbility: "SELF_AMEND",
    },
];
function clone(f, idSuffix) {
    return { ...f, id: `${f.id}-${idSuffix}` };
}
export function makeMockTeamA() {
    return {
        id: "team-a",
        playerId: "player-a",
        name: "Bull Pen",
        finis: [
            clone(mockFinis[1], "a"), // SOL frontline (fast)
            clone(mockFinis[0], "a"), // ETH midline
            clone(mockFinis[2], "a"), // BTC backline (tank)
        ],
    };
}
export function makeMockTeamB() {
    return {
        id: "team-b",
        playerId: "player-b",
        name: "Liquidity Hounds",
        finis: [
            clone(mockFinis[3], "b"), // DOGE frontline
            clone(mockFinis[5], "b"), // AVAX midline
            clone(mockFinis[4], "b"), // LINK backline
        ],
    };
}
export const allMockFinis = mockFinis;
