import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { DEATH_MODE_CONFIRM_PHRASE } from "../game/deathMode";
import { FiniAvatar } from "./FiniAvatar";
export function DeathModeModal(props) {
    if (!props.open)
        return null;
    const phraseOk = props.confirmInput.trim() === DEATH_MODE_CONFIRM_PHRASE;
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-grape/30 backdrop-blur-sm p-3 overflow-y-auto", children: _jsxs("div", { className: "kcard p-5 max-w-3xl w-full my-6 !border-coral/50", style: { boxShadow: "0 0 0 3px rgba(255,138,138,0.4), 0 20px 50px -20px rgba(240,89,90,0.6)" }, children: [_jsxs("div", { className: "flex items-start justify-between gap-3 mb-3", children: [_jsxs("div", { children: [_jsx("div", { className: "chip bg-coral/20 text-coral", children: "\uD83D\uDC80 warning \u00B7 death mode" }), _jsx("h2", { className: "text-2xl font-display font-bold mt-2 text-ink", children: "This is not a normal battle." }), _jsxs("p", { className: "text-ink/70 mt-2 max-w-prose text-sm leading-relaxed font-semibold", children: ["In Death Mode each side places one Fini at risk. The winner claims the loser's staked Fini. In this MVP, transfer is", " ", _jsx("span", { className: "text-coral font-display font-bold", children: "SIMULATED" }), " only \u2014 your mock ownership ledger updates locally. No mainnet NFT transfer occurs. Real Death Mode requires audited escrow."] })] }), _jsx("button", { onClick: props.onClose, className: "kbtn kbtn-ghost text-xs px-3 py-1.5", children: "Close" })] }), _jsx("div", { className: "grid sm:grid-cols-2 gap-3 mb-3", children: ["teamA", "teamB"].map((side) => {
                        const team = side === "teamA" ? props.playerTeam : props.opponentTeam;
                        const stake = side === "teamA" ? props.stakeA : props.stakeB;
                        const confirmed = side === "teamA" ? props.confirmedA : props.confirmedB;
                        return (_jsxs("div", { className: "kcard-soft p-3", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { className: "label-soft", children: [side === "teamA" ? "Your" : "Opponent", " stake"] }), _jsx("div", { className: `chip text-[10px] ${confirmed ? "bg-mint/20 text-mintDark" : "bg-coral/20 text-coral"}`, children: confirmed ? "✓ confirmed" : "unconfirmed" })] }), _jsx("div", { className: "space-y-1.5", children: team.finis.map((f) => {
                                        const selected = stake === f.id;
                                        return (_jsxs("button", { onClick: () => props.onPickStake(side, f.id), className: `w-full text-left rounded-xl px-2 py-1.5 flex items-center gap-2 transition ${selected
                                                ? "bg-coral/15 ring-2 ring-coral/60"
                                                : "hover:bg-grape/5 ring-1 ring-cloud"}`, children: [_jsx(FiniAvatar, { family: f.family, mood: selected ? "sad" : "ok", size: 26 }), _jsxs("div", { className: "flex-1 text-xs", children: [_jsx("div", { className: "font-display font-bold text-ink", children: f.name }), _jsxs("div", { className: "text-[10px] text-inkSoft font-semibold", children: ["#", f.tokenId ?? "—", " \u00B7 Lv ", f.level] })] }), selected && (_jsx("span", { className: "chip bg-coral/20 text-coral text-[9px]", children: "exposed" }))] }, f.id));
                                    }) }), _jsx("button", { onClick: () => props.onConfirm(side), disabled: !stake || (side === "teamA" && !phraseOk), className: `mt-3 w-full kbtn py-2 text-xs ${!stake || (side === "teamA" && !phraseOk)
                                        ? "kbtn-ghost"
                                        : confirmed
                                            ? "kbtn-mint"
                                            : "kbtn-primary"}`, children: confirmed
                                        ? "✓ Confirmed"
                                        : side === "teamA"
                                            ? "Confirm stake"
                                            : "Opponent auto-confirm (sim)" })] }, side));
                    }) }), _jsxs("div", { className: "kcard-soft p-3 mb-3 !bg-coral/8 !border-coral/30", children: [_jsx("p", { className: "text-sm text-ink font-semibold mb-2", children: "Type the phrase below to enable confirmation for your team." }), _jsx("div", { className: "font-mono text-xs text-coral font-bold mb-2", children: DEATH_MODE_CONFIRM_PHRASE }), _jsx("input", { type: "text", value: props.confirmInput, onChange: (e) => props.onConfirmInput(e.target.value), placeholder: "Type here\u2026", className: "w-full rounded-xl bg-white border-2 border-cloud px-3 py-2 text-sm text-ink focus:outline-none focus:border-coral" }), _jsx("div", { className: `mt-2 text-[10px] font-display font-bold tracking-widest ${phraseOk ? "text-mintDark" : "text-inkSoft"}`, children: phraseOk ? "✓ phrase accepted" : "awaiting phrase" })] }), props.startError && (_jsx("div", { className: "mb-3 kcard-soft px-3 py-2 text-sm text-coral font-semibold !border-coral/40 !bg-coral/10", children: props.startError })), _jsxs("div", { className: "flex flex-col-reverse sm:flex-row gap-2 justify-end", children: [_jsx("button", { onClick: props.onClose, className: "kbtn kbtn-ghost px-4 py-2", children: "Cancel" }), _jsx("button", { onClick: props.onProceed, disabled: !props.confirmedA || !props.confirmedB, className: "kbtn kbtn-primary px-5 py-2", children: "\uD83D\uDC80 Begin Death Mode" })] }), _jsxs("p", { className: "text-[10px] text-inkSoft mt-3 leading-relaxed font-semibold", children: ["MVP behaviour: this transfer is local only. Real Death Mode requires audited NFT escrow, oracle-verified results, explicit both-party signatures, no post-lock cancellation, testnet first, and external audit. See", " ", _jsx("code", { className: "text-grape", children: "src/game/deathMode.ts" }), " for extension points."] })] }) }));
}
